# Generated by Django 5.0.3 on 2024-03-10 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proveedores', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='rol',
            field=models.CharField(choices=[('A', 'aprobador'), ('C', 'colocador')], default=' ', max_length=1),
            preserve_default=False,
        ),
    ]
