# Generated by Django 5.0.3 on 2024-03-10 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proveedores', '0002_customuser_rol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='rol',
            field=models.CharField(choices=[('aprobador', 'aprobador'), ('colocador', 'colocador')], max_length=15),
        ),
    ]
